[qsign]
# 签名服务器地址
# 默认的签名地址延迟有点高
# 如果需求低延迟，请使用香港或其它区域的服务器代理转发即可...
# kritor.support采用CloudFlare代理
server = "https://kritor.support/android/v9.0.20"

# 子服务器 可能不稳定/更快
# server = "http://cdn.kritor.support/android/v9.0.20"

[developer]

[sql]
# 只支持PgSql
# 是否启用数据库
# 启用数据库之后，可以使用获取历史消息功能
enable = true
# postgres://用户名:密码@远程地址/数据库名称
address = "postgres://postgres:postgres@localhost/postgres"

[onebot]

[onebot.http]
# 是否开启主动HTTP
enable = true
# 主动HTTP监听地址
host = "0.0.0.0"
# 主动HTTP监听端口
port = 24601

[onebot.ws]
# 是否开启主动WS
enable = false
# 主动WS监听地址
host = "0.0.0.0"
# 主动WS监听端口
port = 24602

[onebot.pws]
# 是否允许被动WebSocket (反向WS)
enable = false
# 被动WS监听地址
host = "0.0.0.0"
# 被动WS监听端口
port = 24603